/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { B3TR__factory } from "./B3TR__factory";
export { DigitalTwin__factory } from "./DigitalTwin__factory";
